### ISSUE TITLE
clip not working?

### ISSUE THREAD

**Issue by southernanticks** [manups4e/esx_weashops_with_munitions#1]
https://gyazo.com/f6cc562a18a6fe37510379f5cb7cf8c2
 this happens when you select the clip in the weapon shop i get these errors.

**Comment by manups4e** [comment]
That's because you don't know how to add items in a database.. in the name field add clip and in label field add the name you want it to have like "ammo"

**Comment by southernanticks** [comment]
i do  how ever know how to add items to the db sir no need to be disrespectfull

**Comment by manups4e** [comment]
The script is perfect.. but before saying that it's not working just add the item in the right way in the DB.. issue closed
