### ISSUE TITLE
Compare Number With nil Line 121 and 123

### ISSUE THREAD

**Issue by Mokafela** [manups4e/esx_weashops_with_munitions#3]
when i click something to buy there is an error on server/main.lua:121 and error is:

![Screenshot 2020-11-18 133349](https://user-images.githubusercontent.com/40390407/99515842-b9962e00-29a2-11eb-927b-9c3cf89b599d.png)

**Comment by manups4e** [comment]
do you realize this is script has not been updated for over 2 years right?
